wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1665900155
    t:
      1:
      - 3
      - 55
      2:
      - 3
      - 55
      3:
      - 13
      - 19
      4: 3.7.11
      5: 0.12.14
      8:
      - 3
      - 5
hyper_patamter:
  desc: null
  value:
    EfficientNet: 0
    Explore_noise_std: 0.1
    PER_IS: 1
    Policy_noise_std: 0.2
    Regularizer_L2: 0.001
    State_size: 256
    Tau: 0.005
    Train_actor_each_critic: 3
    batch_size: 128
    gamma: 0.95
    learning_rate_Actor: 0.0001
    learning_rate_Critic: 0.0002
    semantic_segmentation: 0
