wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1666233734
    t:
      1:
      - 3
      - 55
      3:
      - 13
      4: 3.7.11
      5: 0.12.14
      8:
      - 5
